### ISSUE TITLE
希望能添加定义文件

### ISSUE THREAD

**Issue by LuoTR** [iamscottxu/openBSE#1]
目前没有定义文件，代码补全功能不能发挥作用，希望能够添加定义文件

**Comment by iamscottxu** [comment]
感谢支持，近期计划更新，会恢复一些错误，增加ts定义文件，还有一些其他功能。

**Comment by iamscottxu** [comment]
已经更新ts定义文件。

**Comment by iamscottxu** [comment]
如果还有其他问题，新建issue反馈，本issue关闭。
