### ISSUE TITLE
循环播放

### ISSUE THREAD

**Issue by morrxy** [iamscottxu/openBSE#2]
请问是否能增加一个循环播放功能？我的场景是没有视频，只播放弹幕，弹幕是api获取的列表。播放完就没了。现在是自己拿api数据凑一个比较大的条数再播放，这样播放的时间就长些。找了一下，没有发现播放完的事件，也没有循环播放功能。

**Comment by iamscottxu** [comment]
解决思路：自定义时间基准，定时重置时间基准，定时向弹幕缓冲区添加弹幕。
示例：
1、定义开始时间变量。
```JavaScript
let startTime = new Date().getTime();
```
2、定义时间基准获取方法。
```JavaScript
function clock() {
    let time = new Date().getTime() - startTime;
    if (time >= [单次循环总时间]) {
        startTime = new Date().getTime();
        time = 0;
        for (var i = 0; i < [弹幕总数]; i++) generalEngine.add([弹幕信息]);
    }
    return time;
}
```
2、初始化时，使用自定义的时间基准。
```JavaScript
let generalEngine = new openBSE.GeneralEngine(document.getElementById('BulletScreensDiv'), {
        clock: clock
}, 'canvas');
```

如果上面的方法还有任何问题可回复。

**Comment by morrxy** [comment]
请问如何知道最后一个弹幕的出现时间呢？每条弹幕的播放时间乘总条数吗？好像无法拿到每条弹幕的播放时间

**Comment by iamscottxu** [comment]
你在加载弹幕时有一个startTime参数，这是你自己定义的，即为弹幕出现时间。你需要找到弹幕数组中startTime最大的那个。

**Comment by iamscottxu** [comment]
startTime的弹幕播放时间是相对于时间基准的。

**Comment by morrxy** [comment]
可以循环了，谢谢。另外，最后一条出现后，是不是应该调一下cleanBuffer，不调的话时间长了会不会爆内存？

**Comment by iamscottxu** [comment]
不会的，因为弹幕缓冲区的弹幕播放完就清除了。
