### ISSUE TITLE
[bug] 弹幕显示隐藏bug

### ISSUE THREAD

**Issue by wukaijin** [iamscottxu/openBSE#3]
伟大的作者，您好。
1 报一个bug，css3 模式下显示和隐藏弹幕无效
2 获取 engine 的  Visibility 属性有错误  原因应该是书写错误  _renderer 写成了 renderer
谢谢~

**Comment by iamscottxu** [comment]
感谢反馈，非常感谢。

**Comment by iamscottxu** [comment]
Bug已恢复。
